src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/controller/PhotoBookController.java, src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/RefreshToken.java, src/main/java/com/example/ai_jeju/domain/Restaurant.java, src/main/java/com/example/ai_jeju/domain/Stay.java, src/main/java/com/example/ai_jeju/dto/SignUpRequest.java, src/main/java/com/example/ai_jeju/generator/NickNameGenerator.java, src/main/java/com/example/ai_jeju/handler/SignUpHandler.java, src/main/java/com/example/ai_jeju/repository/ChildRepository.java, src/main/java/com/example/ai_jeju/repository/MainListRepository.java, src/main/java/com/example/ai_jeju/repository/RefreshTokenRepository.java, src/main/java/com/example/ai_jeju/repository/StayRepository.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/PhotoBookService.java, src/main/java/com/example/ai_jeju/service/UserService.java, src/main/java/com/example/ai_jeju/util/CookieUtil.java, src/main/resources/application.properties
=> 숙박, 식당 상세정보 조회

build.gradle, src/main/java/com/example/ai_jeju/config/AppConfig.java, src/main/java/com/example/ai_jeju/config/HeaderCheckInterceptor.java, src/main/java/com/example/ai_jeju/config/WebConfig.java, src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/controller/MyPageController.java, src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/Play.java, src/main/java/com/example/ai_jeju/domain/RefreshToken.java, src/main/java/com/example/ai_jeju/domain/User.java, src/main/java/com/example/ai_jeju/filter/HeaderCheckFilter.java, src/main/java/com/example/ai_jeju/handler/SignUpHandler.java, src/main/java/com/example/ai_jeju/repository/RefreshTokenRepository.java, src/main/java/com/example/ai_jeju/repository/RestaurantRepository.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/UserService.java, src/main/java/com/example/ai_jeju/util/CookieUtil.java, src/main/resources/application.properties
토큰 유효성 검사를 위한 headerInterceptor를 추가하였습니다.
=> FEAT : add a headerInterceptor

build.gradle, src/main/java/com/example/ai_jeju/controller/PhotoBookController.java, src/main/java/com/example/ai_jeju/domain/Stay.java, src/main/java/com/example/ai_jeju/domain/Store.java, src/main/java/com/example/ai_jeju/dto/ChildRequest.java, src/main/java/com/example/ai_jeju/dto/SignUpRequest.java, src/main/java/com/example/ai_jeju/handler/SignUpHandler.java, src/main/java/com/example/ai_jeju/service/UserService.java, src/main/resources/application.properties
restaurant, stay, leisure table들을 stores 테이블로 병합하였습니다.
=> fix : table absorption

src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/service/UserService.java
=> FIX : segregate sign up service

src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/User.java, src/main/java/com/example/ai_jeju/dto/ChildRequest.java, src/main/java/com/example/ai_jeju/dto/MyPageResponse.java, src/main/java/com/example/ai_jeju/dto/SignUpRequest.java, src/main/java/com/example/ai_jeju/handler/SignUpHandler.java, src/main/java/com/example/ai_jeju/repository/ChildRepository.java, src/main/java/com/example/ai_jeju/repository/StoreRepository.java, src/main/java/com/example/ai_jeju/service/MyPageService.java, src/main/java/com/example/ai_jeju/service/UserService.java
=> FEAT : users/mypage

src/main/java/com/example/ai_jeju/domain/Emergency.java
=> 브랜치합친거전체커밋

src/main/java/com/example/ai_jeju/jwt/TokenProvider.java
=> fix : tokenprovider추가

src/main/java/com/example/ai_jeju/handler/StompHandler.java
=> fix : StompHandler추가

src/main/java/com/example/ai_jeju/domain/Album.java, src/main/java/com/example/ai_jeju/domain/Photo.java, src/main/java/com/example/ai_jeju/repository/AlbumRepository.java
child, album oneToOne 매핑
album photos 매핑
어떤 변경 사항이 있나요?
=> [FEAT] album, photos entity mapping

build.gradle, src/main/java/com/example/ai_jeju/config/JacksonConfig.java, src/main/java/com/example/ai_jeju/controller/MyPageController.java, src/main/java/com/example/ai_jeju/domain/Album.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/User.java, src/main/java/com/example/ai_jeju/dto/ModifyMyPageRequest.java, src/main/java/com/example/ai_jeju/exception/UserNotFoundException.java, src/main/java/com/example/ai_jeju/repository/ChildRepository.java, src/main/java/com/example/ai_jeju/repository/UserRepository.java, src/main/java/com/example/ai_jeju/service/MyPageService.java, src/main/java/com/example/ai_jeju/service/UserService.java
가입시 닉네임 중복 가입 불가하도록 설정
마이페이지 필드 선택적 으로 수정가능하게끔 함
어떤 변경 사항이 있나요?
=> [FIX] 닉네임 중복 가입 불가설정, 마이페이지 필드 선택적 수정

src/main/java/com/example/ai_jeju/controller/BookmarkController.java, src/main/java/com/example/ai_jeju/domain/Bookmark.java, src/main/java/com/example/ai_jeju/repository/BookmarkRepository.java, src/main/java/com/example/ai_jeju/service/BookmarkService.java
사용자가 storeId 관심목록에 추가하기 기능 
만약 이미 관심목록에 넣었다면, 이미 관심목록에 넣었다고 알려줌
어떤 변경 사항이 있나요?
=> [FEAT] 관심목록 추가하기(중복여부 따짐)

src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/repository/RefreshTokenRepository.java, src/main/java/com/example/ai_jeju/service/UserService.java
로그인 응답 수정 
resposne 수정 
문제를 일으키는 myPage 응답 디버깅 코드 삭제
어떤 변경 사항이 있나요?
=> [FIX] 로그인 응답 수정

src/main/java/com/example/ai_jeju/controller/MyPageController.java, src/main/java/com/example/ai_jeju/dto/ChildRequest.java, src/main/java/com/example/ai_jeju/service/UserService.java
마이페이지 부분, 아이 추가하기 기능
어떤 변경 사항이 있나요?
=> [FEAT] 마이페이지 아이 추가기능

src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/controller/MyPageController.java, src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Store.java, src/main/java/com/example/ai_jeju/dto/StoreResponse.java, src/main/java/com/example/ai_jeju/repository/BookmarkRepository.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/UserService.java
회원가입 응답수정, deatailIst 조회 응답수정
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
=> [FIX] 회원가입 응답수정, detailist 응답수정

build.gradle, src/main/java/com/example/ai_jeju/controller/ChatController.java, src/main/java/com/example/ai_jeju/domain/ChatMessage.java
어떤 변경 사항이 있나요?
- [ ㅇ] 코드 리팩토링
- [ㅇ ] 빌드 부분 혹은 패키지 매니저 수정
=> fix : chat get error

build.gradle, src/main/java/com/example/ai_jeju/config/HeaderCheckInterceptor.java, src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/controller/UserController.java, src/main/java/com/example/ai_jeju/domain/Calender.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/Media.java, src/main/java/com/example/ai_jeju/dto/MainListResponse.java, src/main/java/com/example/ai_jeju/dto/StoreResponse.java, src/main/java/com/example/ai_jeju/filter/HeaderCheckFilter.java, src/main/java/com/example/ai_jeju/repository/BookmarkRepository.java, src/main/java/com/example/ai_jeju/repository/MediaRepository.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/UserService.java, src/main/resources/application.properties
mainList 응답수정
관심목록 등록여부 추가
store 별 관심목록 수 추가
어떤 변경 사항이 있나요?
- [s] 버그 수정
=> [FIX] mainList 응답수정

src/main/java/com/example/ai_jeju/controller/MainViewController.java
비회원이 홈 조회할 수 있도록
토큰 없이도 mainList 조회 가능하게 함
`@RequestParam(value = "token", required = false)`
어떤 변경 사항이 있나요?
=> [FIX] 비회원 토큰없이도 mainList 조회

src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/dto/DetailListResponse.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java
=> [FIX] requestParam -> requestHeader

src/main/java/com/example/ai_jeju/controller/ChildController.java, src/main/java/com/example/ai_jeju/controller/ScheduleItemController.java, src/main/java/com/example/ai_jeju/domain/Album.java, src/main/java/com/example/ai_jeju/domain/Child.java, src/main/java/com/example/ai_jeju/domain/Schedule.java, src/main/java/com/example/ai_jeju/domain/ScheduleItem.java, src/main/java/com/example/ai_jeju/dto/AddAlbumRequest.java, src/main/java/com/example/ai_jeju/dto/ChildRequest.java, src/main/java/com/example/ai_jeju/dto/ChildResponseDto.java, src/main/java/com/example/ai_jeju/repository/ScheduleItemRepository.java, src/main/java/com/example/ai_jeju/service/AlbumService.java, src/main/java/com/example/ai_jeju/service/ChildService.java, src/main/java/com/example/ai_jeju/service/ScheduleItemService.java, src/main/java/com/example/ai_jeju/service/UserService.java
아이 추가하기 기능에, imgSrc 타입에러 수정
어떤 변경 사항이 있나요?
=> [FIX] register Child

src/main/java/com/example/ai_jeju/controller/BookmarkController.java, src/main/java/com/example/ai_jeju/repository/BookmarkRepository.java, src/main/java/com/example/ai_jeju/service/BookmarkService.java
=> [FEAT] 관심목록 해제

src/main/java/com/example/ai_jeju/config/JacksonConfig.java, src/main/java/com/example/ai_jeju/controller/BookmarkController.java, src/main/java/com/example/ai_jeju/domain/AlbumItemOption.java, src/main/java/com/example/ai_jeju/domain/Bookmark.java, src/main/java/com/example/ai_jeju/dto/BookMarkItem.java, src/main/java/com/example/ai_jeju/dto/MyBookmarkResponse.java, src/main/java/com/example/ai_jeju/repository/BookmarkRepository.java, src/main/java/com/example/ai_jeju/repository/StoreRepository.java, src/main/java/com/example/ai_jeju/service/BookmarkService.java, src/main/java/com/example/ai_jeju/service/ChildService.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/MyPageService.java
=> [FEAT] 관심목록 조회하기

src/main/java/com/example/ai_jeju/controller/ChildController.java, src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/controller/MyJejuController.java, src/main/java/com/example/ai_jeju/dto/ChildDetailResponse.java, src/main/java/com/example/ai_jeju/dto/ChildResponseDto.java, src/main/java/com/example/ai_jeju/dto/MyJejuChildDto.java, src/main/java/com/example/ai_jeju/dto/MyJejuMyDto.java, src/main/java/com/example/ai_jeju/dto/MyJejuResponse.java, src/main/java/com/example/ai_jeju/service/ChildService.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java, src/main/java/com/example/ai_jeju/service/MyJejuService.java
=> [FEAT] 마이제주 조회하기

src/main/java/com/example/ai_jeju/controller/MyJejuController.java, src/main/java/com/example/ai_jeju/dto/ChildDetailResponse.java, src/main/java/com/example/ai_jeju/service/MyJejuService.java
=> [FEAT] 마아제주 아이상세조회

src/main/java/com/example/ai_jeju/dto/MyJejuMyDto.java, src/main/java/com/example/ai_jeju/service/MyJejuService.java
마이제주>마이페이지 응답 닉네임필드  추가
어떤 변경 사항이 있나요?
=> [FIX] 마이제주>마이페이지 닉네임필드  추가

src/main/java/com/example/ai_jeju/controller/TokenController.java
=> [FEAT] 토큰 유효성 검사 API

src/main/java/com/example/ai_jeju/dto/ChildDetailResponse.java, src/main/java/com/example/ai_jeju/dto/MyJejuChildDto.java, src/main/java/com/example/ai_jeju/service/MyJejuService.java
=> [FIX] 아이 개월수 응답 추가

src/main/java/com/example/ai_jeju/dto/MyJejuChildDto.java, src/main/java/com/example/ai_jeju/service/MyJejuService.java
=> [FIX] 마이제주 이름 필드 추가

src/main/java/com/example/ai_jeju/controller/ChildController.java, src/main/java/com/example/ai_jeju/controller/MyJejuController.java, src/main/java/com/example/ai_jeju/controller/TokenController.java, src/main/java/com/example/ai_jeju/jwt/TokenProvider.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java
[FIX] 토큰 만료시간출력
어떤 변경 사항이 있나요?
=> [FIX] 토큰 만료시간출력

src/main/java/com/example/ai_jeju/controller/MainViewController.java, src/main/java/com/example/ai_jeju/dto/DetailListResponse.java, src/main/java/com/example/ai_jeju/service/MainVIewService.java
=> fix : nokidsdetail반환수정

src/main/java/com/example/ai_jeju/controller/ChatController.java
=> fix : sse buffering

src/main/java/com/example/ai_jeju/controller/ChatController.java
=> fix : sse data

src/main/java/com/example/ai_jeju/controller/ChatController.java
=> fix : sse cors

src/main/java/com/example/ai_jeju/controller/ChatController.java
=> fix : sse cors fix

src/main/java/com/example/ai_jeju/controller/ChatController.java
=> fix : allow origin

src/main/java/com/example/ai_jeju/config/WebConfig.java, src/main/java/com/example/ai_jeju/controller/ChatController.java, src/main/java/com/example/ai_jeju/service/NotificationService.java
=> feat : sse 3초마다 데이터 전송

src/main/java/com/example/ai_jeju/controller/ChatController.java, src/main/java/com/example/ai_jeju/service/NotificationService.java
=> fix : sse string -> json
